apiVersion: batch/v1
kind: Job
metadata:
  name: diskspd-node-${NODE_NUM}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        diskspd: diskspd-multi
        node-test: node-${NODE_NUM}
    spec:
      nodeSelector:
        msft.microsoft/nodepool-name: benchmark-c74bef92-storage2
      affinity:
        # Ensure pods spread across nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: diskspd
                    operator: In
                    values:
                      - diskspd-multi
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: diskspd
          image: ghcr.io/mischavandenburg/diskspd:latest

          # resources:
          #   requests:
          #     cpu: "30820m"

          args:
            - "-b64K" # Block size of 4K
            - "-r64K" # Random IO with 4K alignment
            - "-o16" # Outstanding IO requests per target per thread
            - "-t4" # Number of threads
            # - "-d120" # Test duration of 60 seconds
            - "-d60" # Test duration of 60 seconds
            - "-Sh" # Disable software and hardware caching
            - "-c1G" # Create a 1GB test file
            - "-w100" # Write percentage
            - "-L" # Capture latency information
            - "/volume/testfile"


          # imagePullPolicy: Always
          imagePullPolicy: IfNotPresent

          securityContext:
            privileged: true

          volumeMounts:
            - name: vol
              mountPath: /volume/
            - name: dev
              mountPath: /dev

      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: diskspd-pvc-node-${NODE_NUM}
        - name: dev
          hostPath:
            path: /dev

  backoffLimit: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diskspd-pvc-node-${NODE_NUM}
spec:
  # storageClassName: managed-premium
  # storageClassName: managed-csi-premium
  # storageClassName: aks-hci-disk-custom-vol2
  storageClassName: aks-hci-disk-custom-vol2-512
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
